version: "3"

services:
  app:
    container_name: app
    build: .
    environment:
      - MONGO_URL=mongo
      - REDIS_URL=redis
    ports:
      - "3009:3009"
    volumes:
      - .:/usr/app
    links:
      - mongo
      - redis

  mongo:
    container_name: mongoDB
    image: mongo
    command: mongod --quiet --logpath /dev/null 
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"

    
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./data:/redis/db
    ports:
      - "6378:6379"